name: Feature Request
description: Request a new or improved a feature in JS-CARDIO
labels: [enhancement]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us grow. ❤️
        Please search GitHub for a similar [issue](https://github.com/bbodine1/js-cardio/issues) or [PR](https://github.com/bbodine1/js-cardio/pulls)  before submitting a new issue.

  - type: textarea
    id: information
    attributes:
      label: Information
      description: Tell us what you want to be added to JS-CARDIO
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe any alternatives/workarounds you're currently using

  - type: checkboxes
    id: assistance
    attributes:
      label: I would be willing to submit a PR to fix this issue
      description: Assistance is provided if you need help submitting a pull request
      options:
        - label: 'Yes'
        - label: 'No'
